// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Supports only Android and iOS platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Only Android and iOS are supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxJdj7qo8w8FKZD4sIwkz6wTJihDiQJY',
    appId: '1:935710220800:android:a5da1d236dea7d76cd2ee5',
    messagingSenderId: '935710220800',
    projectId: 'crii-focus-today',
    databaseURL: 'https://crii-focus-today-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crii-focus-today.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3k1vg9rBCwBqoEQ3F8c7rZMCGpAtAGY',
    appId: '1:935710220800:ios:1b3850b64fd98b89cd2ee5',
    messagingSenderId: '935710220800',
    projectId: 'crii-focus-today',
    databaseURL: 'https://crii-focus-today-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crii-focus-today.firebasestorage.app',
    iosBundleId: 'com.eagletv.eagleTv',
  );

}